version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Loganito2
      - DB_NAME=parentportal
      - JWT_SECRET=super_secret_jwt_key_here_or_in_env
    volumes:
      # Map container upload changes back to local host folder for persistence
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Loganito2
      - POSTGRES_DB=parentportal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount initialization scripts. PG runs these automatically if DB doesn't exist yet!
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    restart: unless-stopped

volumes:
  pgdata:
