import React, { createContext, useContext, useState, useEffect } from 'react';

const ThemeLanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: "Dashboard",
    all_documents: "All Documents",
    approval_queue: "Approval Queue",
    staff_directory: "Staff Directory",
    archive: "Archive",
    help_center: "Help Center",
    sign_out: "Sign Out",
    new_entry: "New Entry",
    new_request: "New Request",
    search_records: "Search records...",
    search_registry: "Search registry...",
    filter_list: "Filter List",
    add_new_staff: "Add New Staff",
    staff_registry: "Staff Registry",
    active_requests: "ACTIVE REQUESTS",
    awaiting_action: "Awaiting processing or action",
    parent_dashboard: "Parent Dashboard",
    recent_requests: "Recent Document Requests",
    view_all: "View All",
    requests: "Requests",
    verification: "Verification",
    user_management: "User Management",
    // Profile page
    account_settings: "Account Settings",
    manage_personal_profile: "Manage your personal profile and security boundaries.",
    profile_picture: "Profile Picture",
    supported_formats: "Supported formats: JPG, PNG. Max size: 2MB.",
    personal_identification: "Personal Identification",
    full_legal_name: "Full Legal Name",
    registered_email: "Registered Email",
    access_node_clearance: "Access Node Clearance",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    update_password: "Update Password",
    updating: "Updating...",
    enter_current_password: "Enter your current password",
    at_least_6_chars: "At least 6 characters",
    repeat_new_password: "Repeat new password",
    uploading_picture: "Uploading picture...",
    pw_not_match: "New passwords do not match.",
    pw_min_length: "New password must be at least 6 characters.",
    pw_success: "Password updated successfully!",
    // BankDetails page
    bank_transfer_details: "Bank Transfer Details",
    document_fee_payment: "Document Fee Payment",
    document_processing_details: "Document Processing Details",
    bank_details_instruction: "To finalize your document request, please initiate a transfer for the processing fee from your bank account using the details below. Once completed, upload your receipt using the portal or via email to registrar@bishopmartin.edu.",
    official_receiving_account: "OFFICIAL RECEIVING ACCOUNT",
    bank_name: "BANK NAME",
    account_holder: "ACCOUNT HOLDER",
    account_number: "ACCOUNT NUMBER (SWIFT/IBAN)",
    branch_code: "BRANCH CODE / ROUTING",
    transfer_reference: "TRANSFER REFERENCE (MANDATORY)",
    transfer_reference_desc: "Please copy this exact text into your bank's reference field so we can match your payment.",
    copy_reference: "Copy Reference",
    copied: "Copied!",
    upload_receipt: "Upload Receipt",
    upload_receipt_desc: "Supported formats: PDF, JPG, PNG (Max 5MB). Please ensure all details are legible.",
    select_receipt_file: "Select Receipt File",
    submit_receipt: "Submit Receipt",
    need_assistance: "Need Assistance?",
    need_assistance_desc: "Contact the Finance Office at finance@bishopmartin.edu or call +501 223-0192 for payment issues.",
    no_payments_due: "No Payments Due",
    no_payments_due_desc: "You currently have no pending document requests requiring payment.",
    document_fee: "Document Fee",
    processing_fees_included: "Processing and administrative fees included",
    timeline: "Timeline",
    request_summary: "Request Summary",
    reference: "Reference",
    student: "Student",
    grade_level: "Grade Level",
    due_date: "Due Date",
    payment_awaiting_confirmation: "Payment Awaiting Confirmation",
    uploading: "Uploading...",
    upload_transfer_receipt: "Upload Transfer Receipt"
  },
  es: {
    dashboard: "Tablero",
    all_documents: "Todos los Documentos",
    approval_queue: "Cola de Aprobación",
    staff_directory: "Directorio de Personal",
    archive: "Archivo",
    help_center: "Centro de Ayuda",
    sign_out: "Cerrar Sesión",
    new_entry: "Nueva Entrada",
    new_request: "Nueva Solicitud",
    search_records: "Buscar registros...",
    search_registry: "Buscar directorio...",
    filter_list: "Filtrar Lista",
    add_new_staff: "Agregar Personal",
    staff_registry: "Registro de Personal",
    active_requests: "SOLICITUDES ACTIVAS",
    awaiting_action: "En espera de procesamiento o acción",
    parent_dashboard: "Panel de Padres",
    recent_requests: "Solicitudes de Documentos Recientes",
    view_all: "Ver Todo",
    requests: "Solicitudes",
    verification: "Verificación",
    user_management: "Gestión de Usuarios",
    // Profile page
    account_settings: "Configuración de la cuenta",
    manage_personal_profile: "Gestione su perfil personal y límites de seguridad.",
    profile_picture: "Foto de perfil",
    supported_formats: "Formatos admitidos: JPG, PNG. Tamaño máx: 2MB.",
    personal_identification: "Identificación personal",
    full_legal_name: "Nombre legal completo",
    registered_email: "Correo electrónico registrado",
    access_node_clearance: "Nivel de acceso del nodo",
    change_password: "Cambiar contraseña",
    current_password: "Contraseña actual",
    new_password: "Nueva contraseña",
    confirm_new_password: "Confirmar nueva contraseña",
    update_password: "Actualizar contraseña",
    updating: "Actualizando...",
    enter_current_password: "Introduzca su contraseña actual",
    at_least_6_chars: "Al menos 6 caracteres",
    repeat_new_password: "Repita la nueva contraseña",
    uploading_picture: "Subiendo foto...",
    pw_not_match: "Las nuevas contraseñas no coinciden.",
    pw_min_length: "La nueva contraseña debe tener al menos 6 caracteres.",
    pw_success: "¡Contraseña actualizada con éxito!",
    // BankDetails page
    bank_transfer_details: "Detalles de Transferencia Bancaria",
    document_fee_payment: "Pago de Tasa de Documento",
    document_processing_details: "Detalles de Procesamiento de Documentos",
    bank_details_instruction: "Para finalizar su solicitud de documento, inicie una transferencia para la tasa de procesamiento desde su cuenta bancaria utilizando los detalles a continuación. Una vez completado, suba su recibo usando el portal o por correo electrónico a registrar@bishopmartin.edu.",
    official_receiving_account: "CUENTA RECEPTORA OFICIAL",
    bank_name: "NOMBRE DEL BANCO",
    account_holder: "TITULAR DE LA CUENTA",
    account_number: "NÚMERO DE CUENTA (SWIFT/IBAN)",
    branch_code: "CÓDIGO DE SUCURSAL / RUTA",
    transfer_reference: "REFERENCIA DE TRANSFERENCIA (OBLIGATORIO)",
    transfer_reference_desc: "Copie este texto exacto en el campo de referencia de su banco para que podamos identificar su pago.",
    copy_reference: "Copiar Referencia",
    copied: "¡Copiado!",
    upload_receipt: "Subir Recibo",
    upload_receipt_desc: "Formatos admitidos: PDF, JPG, PNG (Máx 5MB). Asegúrese de que todos los detalles sean legibles.",
    select_receipt_file: "Seleccionar Archivo de Recibo",
    submit_receipt: "Enviar Recibo",
    need_assistance: "¿Necesita Ayuda?",
    need_assistance_desc: "Póngase en contacto con la Oficina de Finanzas en finance@bishopmartin.edu o llame al +501 223-0192 para problemas de pago.",
    no_payments_due: "Sin Pagos Pendientes",
    no_payments_due_desc: "Actualmente no tiene solicitudes de documentos pendientes que requieran pago.",
    document_fee: "Tasa de Documento",
    processing_fees_included: "Tasas de procesamiento y administración incluidas",
    timeline: "Cronograma",
    request_summary: "Resumen de la Solicitud",
    reference: "Referencia",
    student: "Estudiante",
    grade_level: "Grado",
    due_date: "Fecha de Vencimiento",
    payment_awaiting_confirmation: "Pago en Espera de Confirmación",
    uploading: "Subiendo...",
    upload_transfer_receipt: "Subir Recibo de Transferencia"
  },
  bz: {
    dashboard: "Dashboard",
    all_documents: "All di Paper dem",
    approval_queue: "Approve Line",
    staff_directory: "Workers List",
    archive: "Old Records",
    help_center: "Help Spot",
    sign_out: "Log Out",
    new_entry: "New Ting",
    new_request: "New Request",
    search_records: "Look fi paper dem...",
    search_registry: "Look fi worker dem...",
    filter_list: "Sort List",
    add_new_staff: "Add New Worker",
    staff_registry: "School Workers",
    active_requests: "ACTIVE REQUESTS DEM",
    awaiting_action: "Waiting fi check up",
    parent_dashboard: "Parent Yard",
    recent_requests: "New Request Dem",
    view_all: "See All",
    requests: "Request dem",
    verification: "Check Identity",
    user_management: "Profile Work",
    // Profile page
    account_settings: "Akaunt Settings",
    manage_personal_profile: "Manage yuh profile and security boundary dem.",
    profile_picture: "Profile Picksha",
    supported_formats: "Weh work: JPG, PNG. Max size: 2MB.",
    personal_identification: "Who Yuh Be",
    full_legal_name: "Government Name",
    registered_email: "Registered Email",
    access_node_clearance: "Weh Yuh Can Do",
    change_password: "Change Password",
    current_password: "Old Password",
    new_password: "New Password",
    confirm_new_password: "Check New Password Again",
    update_password: "Save New Password",
    updating: "Saving...",
    enter_current_password: "Type yuh old password",
    at_least_6_chars: "At least 6 letters/numbers",
    repeat_new_password: "Type new password again",
    uploading_picture: "Uploading picksha...",
    pw_not_match: "Di new password dem no match up.",
    pw_min_length: "Di new password must have at least 6 letters/numbers.",
    pw_success: "Password change up good!",
    // BankDetails page
    bank_transfer_details: "Bank Transfer Info",
    document_fee_payment: "Document Fee Payment",
    document_processing_details: "Paper Processing Info",
    bank_details_instruction: "Fi finish yuh request, send di money from yuh bank using di info down yah. When yuh done, upload yuh receipt yah or send email to registrar@bishopmartin.edu.",
    official_receiving_account: "OFFICIAL RECEIVING ACCOUNT",
    bank_name: "BANK NAME",
    account_holder: "ACCOUNT HOLDER",
    account_number: "ACCOUNT NUMBER",
    branch_code: "BRANCH CODE",
    transfer_reference: "TRANSFER REFERENCE (MANDATORY)",
    transfer_reference_desc: "Make sure yuh copy dis exact text into yuh bank reference box so we know dah yuh pay.",
    copy_reference: "Copy Reference",
    copied: "Copied!",
    upload_receipt: "Upload Receipt",
    upload_receipt_desc: "Weh work: PDF, JPG, PNG (Max 5MB). Make sure everything clear.",
    select_receipt_file: "Select Receipt File",
    submit_receipt: "Submit Receipt",
    need_assistance: "Need Help?",
    need_assistance_desc: "Contact finance office at finance@bishopmartin.edu or call +501 223-0192 fi any money problem.",
    no_payments_due: "No Payment Due",
    no_payments_due_desc: "Yuh no have no document request weh need money right now.",
    document_fee: "Paper Cost",
    processing_fees_included: "Processing fee deh inside",
    timeline: "Time Line",
    request_summary: "Request Summary",
    reference: "Ref number",
    student: "Student",
    grade_level: "Class",
    due_date: "Due Date",
    payment_awaiting_confirmation: "Waiting fi check payment",
    uploading: "Saving...",
    upload_transfer_receipt: "Upload Receipt File"
  },
  fr: {
    dashboard: "Tableau de Bord",
    all_documents: "Tous les Documents",
    approval_queue: "File d'Attente d'Approbation",
    staff_directory: "Répertoire du Personnel",
    archive: "Archive",
    help_center: "Centre d'Aide",
    sign_out: "Se Déconnecter",
    new_entry: "Nouvelle Entrée",
    new_request: "Nouvelle Demande",
    search_records: "Rechercher des dossiers...",
    search_registry: "Rechercher dans le registre...",
    filter_list: "Filtrer la Liste",
    add_new_staff: "Ajouter du Personnel",
    staff_registry: "Registre du Personnel",
    active_requests: "DEMANDES ACTIVES",
    awaiting_action: "En attente de traitement ou d'action",
    parent_dashboard: "Tableau des Parents",
    recent_requests: "Demandes de Documents Récentes",
    view_all: "Voir Tout",
    requests: "Demandes",
    verification: "Vérification",
    user_management: "Gestion des Utilisateurs",
    // Profile page
    account_settings: "Paramètres du compte",
    manage_personal_profile: "Gériez votre profil personnel et vos limites de sécurité.",
    profile_picture: "Photo de profil",
    supported_formats: "Formats supportés: JPG, PNG. Taille max: 2Mo.",
    personal_identification: "Identification personnelle",
    full_legal_name: "Nom légal complet",
    registered_email: "Adresse e-mail enregistrée",
    access_node_clearance: "Niveau d'accès du nœud",
    change_password: "Changer le mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_new_password: "Confirmer le nouveau mot de passe",
    update_password: "Mettre à jour",
    updating: "Mise à jour...",
    enter_current_password: "Entrez votre mot de passe actuel",
    at_least_6_chars: "Au moins 6 caractères",
    repeat_new_password: "Répétez le nouveau mot de passe",
    uploading_picture: "Téléchargement de la photo...",
    pw_not_match: "Les nouveaux mots de passe ne correspondent pas.",
    pw_min_length: "Le nouveau mot de passe doit comporter au moins 6 caractères.",
    pw_success: "Mot de passe mis à jour avec succès !",
    // BankDetails page
    bank_transfer_details: "Détails du Virement Bancaire",
    document_fee_payment: "Paiement des Frais de Document",
    document_processing_details: "Détails du Traitement des Documents",
    bank_details_instruction: "Pour finaliser votre demande de document, veuillez effectuer un virement pour les frais de traitement depuis votre compte bancaire en utilisant les coordonnées ci-dessous. Une fois terminé, téléchargez votre reçu via le portail ou par e-mail à registrar@bishopmartin.edu.",
    official_receiving_account: "COMPTE DE RÉCEPTION OFFICIEL",
    bank_name: "NOM DE LA BANQUE",
    account_holder: "TITULAIRE DU COMPTE",
    account_number: "NUMÉRO DE COMPTE (SWIFT/IBAN)",
    branch_code: "CODE DE SUCCURSALE / ROUTAGE",
    transfer_reference: "RÉFÉRENCE DE TRANSFERT (OBLIGATOIRE)",
    transfer_reference_desc: "Veuillez copier ce texte exact dans le champ de référence de votre banque afin que nous puissions faire correspondre votre paiement.",
    copy_reference: "Copier la Référence",
    copied: "Copié !",
    upload_receipt: "Télécharger le Reçu",
    upload_receipt_desc: "Formats supportés: PDF, JPG, PNG (Max 5Mo). Veuillez vous assurer que tous les détails sont lisibles.",
    select_receipt_file: "Sélectionner le Fichier du Reçu",
    submit_receipt: "Soumettre le Reçu",
    need_assistance: "Besoin d'Aide ?",
    need_assistance_desc: "Contactez le bureau des finances à finance@bishopmartin.edu ou appelez le +501 223-0192 pour les problèmes de paiement.",
    no_payments_due: "Aucun Paiement Dû",
    no_payments_due_desc: "Vous n'avez actuellement aucune demande de document en attente nécessitant un paiement.",
    document_fee: "Frais de Document",
    processing_fees_included: "Frais de traitement et d'administration inclus",
    timeline: "Chronologie",
    request_summary: "Résumé de la Demande",
    reference: "Référence",
    student: "Élève",
    grade_level: "Niveau Scolaire",
    due_date: "Date d'Échéance",
    payment_awaiting_confirmation: "Paiement en Attente de Confirmation",
    uploading: "Chargement...",
    upload_transfer_receipt: "Télécharger le Reçu de Virement"
  }
};

export const ThemeLanguageProvider = ({ children }) => {
  const [theme, setTheme] = useState(() => localStorage.getItem('app-theme') || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem('app-lang') || 'en');

  useEffect(() => {
    localStorage.setItem('app-theme', theme);
    if (theme === 'dark') {
      document.body.classList.add('dark');
    } else {
      document.body.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('app-lang', language);
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <ThemeLanguageContext.Provider value={{ theme, toggleTheme, language, setLanguage, t }}>
      {children}
    </ThemeLanguageContext.Provider>
  );
};

export const useSettings = () => useContext(ThemeLanguageContext);
